language: go

go:
  - 1.12.x
  - 1.13.x
  
env:
  - GO111MODULE=on REDISEEN_REDIS_URI="redis://:@localhost:6400" REDISEEN_KEY_PATTERN_EXPOSED="^key:[.]*" REDISEEN_TEST_MODE=true REDISEEN_DB_EXPOSED=0-5

before_install:
  - go get -v -t -d ./...

script:
  - go test -cover -race -coverprofile=coverage.txt -covermode=atomic github.com/xd-deng/rediseen

after_success:
  - bash <(curl -s https://codecov.io/bash)
