language: go

go:
  - 1.11.x
  - 1.12.x
  - 1.13.x
  
env:
  - REDISEEN_REDIS_URI=redis://:@localhost:6400 REDISEEN_KEY_PATTERN_EXPOSED="^key:[.]* REDISEEN_TEST_MODE=true REDISEEN_DB_EXPOSED=0-5

script:
  - go test -cover .
