apiVersion: apps/v1
kind: Deployment
metadata:
  name: rediseen-deployment
  labels:
    app: rediseen
spec:
  replicas: 2
  selector:
    matchLabels:
      app: rediseen
  template:
    metadata:
      labels:
        app: rediseen
    spec:
      containers:
        - name: rediseen
          image: xddeng/rediseen:latest
          ports:
            - containerPort: 8000
          envFrom:
            - secretRef:
                name: rediseen-secret
            - configMapRef:
                name: rediseen-configmap