name: Rediseen_nightly_build_release
on: [push]

jobs:
  build:
    name: Publish-to-DockerHub
    runs-on: ubuntu-latest

    steps:      
      - name: Check out code
        uses: actions/checkout@v1
          
      - name: Build Rediseen Nightly Build Image
        run: |
          docker build -t ${{ secrets.DOCKERHUB_ID }}/rediseen:nightly .

      - name: Push to DockerHub
        run: |
          echo ${{ secrets.DOCKERHUB_PD }} | docker login --username=${{ secrets.DOCKERHUB_ID }} --password-stdin
          docker push ${{ secrets.DOCKERHUB_ID }}/rediseen:nightly
          docker logout
          
