name: RediseenIntegrationTest
on:
  push:
    branches:
      - '*'
  schedule:
    - cron:  '0 0 * * *'

jobs:
  build:
    name: IntegrationTest
    runs-on: ubuntu-latest

    services:
      redis:
        image: redis
        ports:
          - 6379/tcp

    steps:
    - name: Set up Go 1.12
      uses: actions/setup-go@v1
      with:
        go-version: 1.12
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v1

    - name: Get dependencies
      run: |
        go get -v -t -d ./...
        if [ -f Gopkg.toml ]; then
            curl https://raw.githubusercontent.com/golang/dep/master/install.sh | sh
            dep ensure
        fi

    - name: Integration Test
      env:
        REDISEEN_PORT: 9000
        REDISEEN_KEY_PATTERN_EXPOSED: "^key:[.]*"
        REDISEEN_KEY_PATTERN_EXPOSE_ALL: false
        REDISEEN_REDIS_URI: redis://:@localhost:${{ job.services.redis.ports['6379'] }}
        REDISEEN_DB_EXPOSED: 0-5
      run: |
        sudo apt-get install redis-tools
        sudo apt-get install jq
        
        check_by_jq_field () {
            # $1: URL to Curl
            # $2: field in the JSON response to check 
            # $3: value expected for the field specified

            echo Calling: $1
            echo Checking Field: $2
            echo Expecting Field: $3

            OUTPUT=$(curl -s $1)
            echo $OUTPUT
            RESULT=$(echo $OUTPUT | jq -r '.'$2)
            if [ "$RESULT" == "$3" ]; then
                echo OK
            else
                echo "You're on fire"
                exit 1
            fi
            echo
        } 

        go build -v .

        ./rediseen -d start

        check_by_jq_field http://localhost:9000 error "Usage: /db, /db/key, /db/key/index, or /db/key/field"
        check_by_jq_field http://localhost:9000/0/key:1/1/1 error "Usage: /db, /db/key, /db/key/index, or /db/key/field"
        check_by_jq_field http://localhost:9000/0 count "0"
        check_by_jq_field http://localhost:9000/0 total "0"
        check_by_jq_field http://localhost:9000/0/key:1 error "Key provided does not exist."
        check_by_jq_field http://localhost:9000/0/key:1/1 error "Key provided does not exist."
        check_by_jq_field http://localhost:9000/0/no_access_key error "Key pattern is forbidden from access"
        check_by_jq_field http://localhost:9000/6 error "DB 6 is not exposed"
        check_by_jq_field http://localhost:9000/6/key:1 error "DB 6 is not exposed"

        echo "set key:1 Rediseen" | redis-cli -p ${{ job.services.redis.ports['6379'] }}
        check_by_jq_field http://localhost:9000/0/key:1 value "Rediseen"
        check_by_jq_field http://localhost:9000/0/key:1 type "string"
        check_by_jq_field http://localhost:9000/0/key:1/2 value "d"
        check_by_jq_field http://localhost:9000/0/key:1/2 type "string"

        echo "hset key:2 year 2019" | redis-cli -p ${{ job.services.redis.ports['6379'] }}
        echo "hset key:2 project rediseen" | redis-cli -p ${{ job.services.redis.ports['6379'] }}
        check_by_jq_field http://localhost:9000/0/key:2 type "hash"
        check_by_jq_field http://localhost:9000/0/key:2/year type "hash"
        check_by_jq_field http://localhost:9000/0/key:2/year value "2019"
        check_by_jq_field http://localhost:9000/0/key:2/project type "hash"
        check_by_jq_field http://localhost:9000/0/key:2/project value "rediseen"
        
        echo "lpush key:3 github" | redis-cli -p ${{ job.services.redis.ports['6379'] }}
        echo "lpush key:3 coding" | redis-cli -p ${{ job.services.redis.ports['6379'] }}
        echo "rpush key:3 ENJOY" | redis-cli -p ${{ job.services.redis.ports['6379'] }}
        check_by_jq_field http://localhost:9000/0/key:3 type "list"
        check_by_jq_field http://localhost:9000/0/key:3/0 value "coding"
        check_by_jq_field http://localhost:9000/0/key:3/1 value "github"
        check_by_jq_field http://localhost:9000/0/key:3/2 value "ENJOY"

        echo "del key:1" | redis-cli -p ${{ job.services.redis.ports['6379'] }}
        check_by_jq_field http://localhost:9000/0/key:1 error "Key provided does not exist."

        echo "del key:2" | redis-cli -p ${{ job.services.redis.ports['6379'] }}
        check_by_jq_field http://localhost:9000/0/key:2 error "Key provided does not exist."

        echo "del key:3" | redis-cli -p ${{ job.services.redis.ports['6379'] }}
        check_by_jq_field http://localhost:9000/0/key:3 error "Key provided does not exist."
        
        ./rediseen stop    
